import { defineConfig } from "@playwright/test";

/** Isolated module/component tests that do not require a running Agentor
 * installation or authenticated global setup. */
export default defineConfig({
  testDir: ".",
  testMatch: [
    "api/plugin-core.spec.ts",
    "api/plugin-desktop-core.spec.ts",
    "api/plugin-runtime-drain.spec.ts",
    "api/docker-plugin-exec-transport.spec.ts",
    "api/portable-managed-volume-format.spec.ts",
    "api/portable-managed-volume-archive.spec.ts",
    "api/portable-managed-volume-plan.spec.ts",
    "api/portable-managed-volume-journal.spec.ts",
    "api/portable-managed-volume-runtime.spec.ts",
    "api/admin-workspace-store-transactions.spec.ts",
    "api/container-store-quarantine.spec.ts",
    "api/worker-store-durability.spec.ts",
    "api/config-store-integrity.spec.ts",
    "api/worker-config-materialization.spec.ts",
    "api/management-owner-validation.spec.ts",
    "api/instance-backup-*.spec.ts",
    "api/backup-restart-recovery.spec.ts",
    "api/backup-provider-discovery.spec.ts",
    "api/instance-control-plane-coordinator.spec.ts",
    "api/instance-operation-deadline.spec.ts",
    "api/instance-http-adapter.spec.ts",
    "api/instance-snapshot-auth.spec.ts",
    "api/instance-auth-drain.spec.ts",
    "api/instance-barrier-http.spec.ts",
    "api/instance-background-drain.spec.ts",
    "api/instance-update-drain.spec.ts",
    "api/instance-storage-drain.spec.ts",
    "api/instance-backup-config-drain.spec.ts",
    "api/instance-managed-volume-inventory.spec.ts",
    "api/docker-exec-capture-settlement.spec.ts",
    "api/docker-command-exec-transport.spec.ts",
    "api/instance-external-operation-journal.spec.ts",
    "api/instance-export-drain.spec.ts",
    "api/instance-lifecycle-drain.spec.ts",
    "api/instance-worker-store-drain.spec.ts",
    "api/instance-store-drain.spec.ts",
    "api/instance-catalog-store-drain.spec.ts",
    "api/instance-credential-drain.spec.ts",
    "api/instance-recovery-key-drain.spec.ts",
    "api/instance-image-drain.spec.ts",
    "api/image-catalog-hierarchy.spec.ts",
    "api/worker-export-drain.spec.ts",
    "api/worker-export-consumer.spec.ts",
    "api/docker-archive-transfer.spec.ts",
    "api/management-control-plane.spec.ts",
    "api/management-console-drain.spec.ts",
    "api/terminal-ws-drain.spec.ts",
    "api/instance-restore-helper.spec.ts",
    "api/managed-volume-store.spec.ts",
    "api/managed-volume-sizing-control.spec.ts",
    "api/managed-volume-sizing-mcp-authority.spec.ts",
    "api/managed-volume-sizing.spec.ts",
    "api/management-image-backup-domain.spec.ts",
    "api/management-worker-domain.spec.ts",
    "api/provider-http.spec.ts",
    "api/worker-self-access-policy.spec.ts",
    "api/worker-runtime-policy.spec.ts",
    "api/worker-runtime-admin.spec.ts",
    "api/worker-runtime-recovery-route.spec.ts",
    "api/worker-runtime-backup.spec.ts",
    "api/backup-restore-safety.spec.ts",
    "api/worker-runtime-migration.spec.ts",
    "api/worker-runtime-migration-durability.spec.ts",
    "api/worker-runtime-capacity-accounting.spec.ts",
    "api/worker-runtime-capacity-protocol.spec.ts",
    "api/worker-runtime-capacity-ledger.spec.ts",
    "api/worker-runtime-capacity-rpc.spec.ts",
    "api/worker-runtime-capacity-candidate.spec.ts",
    "api/worker-runtime-capacity-linux-reader.spec.ts",
    "api/worker-runtime-snapshot.spec.ts",
    "api/worker-runtime-image-proof.spec.ts",
    "api/worker-runtime-image-pinning.spec.ts",
    "api/worker-export-format.spec.ts",
    "api/kata-managed-volume-runtime.spec.ts",
    "api/workspace-download-cancellation.spec.ts",
    "api/workspace-access-drain.spec.ts",
    "ui/worker-runtime-recovery.spec.ts",
  ],
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: [["list"]],
  timeout: 30_000,
});
