import { defineConfig } from "@playwright/test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// Module lifecycle tests also exercise real metadata cleanup (e.g. workspace
// tombstones). Scope service singletons before imports; never touch developer
// /data just because no installation stack is running.
if (!process.env.DATA_DIR) {
  const fixtureData = mkdtempSync(join(tmpdir(), "agentor-incus-acceptance-"));
  process.env.DATA_DIR = fixtureData;
  // Managed-storage tests retain bounded recovery records on ambiguity. Never
  // erase their service store automatically when failed fixture cleanup leaves
  // Incus resources for operator diagnosis; successful tests clean exact state.
  if (process.env.INCUS_MANAGED_VOLUME_TEST !== 'true' && process.env.INCUS_MANAGED_BACKUP_TEST !== 'true' &&
      process.env.INCUS_MANAGED_IMPORT_TEST !== 'true' && process.env.INCUS_SELECTED_BACKUP_TEST !== 'true' &&
      process.env.INCUS_SELECTED_IMPORT_TEST !== 'true' && process.env.INCUS_DOCKER_ARCHIVE_PROOF_TEST !== 'true' &&
      process.env.INCUS_DOCKER_IMPORT_TEST !== 'true' && process.env.INCUS_INSTANCE_BACKUP_TEST !== 'true')
    process.once("exit", () => rmSync(fixtureData, { recursive: true, force: true }));
}

/** Fast server-module tests that import utility code directly and therefore do
 * not require a running Agentor installation or authenticated global setup. */
export default defineConfig({
  testDir: ".",
  testMatch: [
    "api/plugin-core.spec.ts",
    "api/plugin-desktop-core.spec.ts",
    "api/portable-managed-volume-format.spec.ts",
    "api/portable-managed-volume-archive.spec.ts",
    "api/incus-canonical-restore-archive.spec.ts",
    "api/incus-canonical-restore-payload.spec.ts",
    "api/incus-selected-restore-archive.spec.ts",
    "api/incus-selected-restore-payload.spec.ts",
    "api/incus-selected-restore.spec.ts",
    "api/incus-selected-archive.spec.ts",
    "api/incus-selected-runtime.spec.ts",
    "api/incus-selected-backup-live.spec.ts",
    "api/incus-docker-archive-live.spec.ts",
    "api/incus-docker-archive.spec.ts",
    "api/incus-offline-docker-script.spec.ts",
    "api/incus-docker-restore-archive.spec.ts",
    "api/incus-docker-restore-script.spec.ts",
    "api/incus-canonical-restore.spec.ts",
    "api/incus-worker-import.spec.ts",
    "api/portable-managed-volume-plan.spec.ts",
    "api/portable-managed-volume-journal.spec.ts",
    "api/portable-managed-volume-runtime.spec.ts",
    "api/incus-managed-archive.spec.ts",
    "api/incus-managed-backup-live.spec.ts",
    "api/admin-workspace-store-transactions.spec.ts",
    "api/container-store-quarantine.spec.ts",
    "api/instance-backup-*.spec.ts",
    "api/instance-native-apply.spec.ts",
    "api/instance-native-helper-process.spec.ts",
    "api/legacy-incus-migration-capture-live.spec.ts",
    "api/legacy-incus-migration-capture.spec.ts",
    "api/legacy-incus-migration-admission.spec.ts",
    "api/legacy-incus-migration-finalize.spec.ts",
    "api/worker-incus-migration-service.spec.ts",
    "api/legacy-incus-migration-public-live.spec.ts",
    "api/instance-restore-helper.spec.ts",
    "api/backup-original-runtime-fence.spec.ts",
    "api/backup-restore-safety.spec.ts",
    "api/backup-restore-cancellation.spec.ts",
    "api/backup-cross-instance-manager.spec.ts",
    "api/backup-restore-runtime-authority.spec.ts",
    "api/managed-volume-store.spec.ts",
    "api/managed-network-update.spec.ts",
    "api/managed-network-authorization.spec.ts",
    "api/managed-network-manager.spec.ts",
    "api/managed-network-hosts.spec.ts",
    "api/managed-network-host-authority.spec.ts",
    "api/incus-managed-docker-bridge.spec.ts",
    "api/worker-group-network-coordinator.spec.ts",
    "api/host-mount-store.spec.ts",
    "api/incus-host-mount-client.spec.ts",
    "api/incus-host-mount-runtime.spec.ts",
    "api/incus-host-mount-live.spec.ts",
    "api/managed-volume-sizing-control.spec.ts",
    "api/managed-volume-sizing-mcp-authority.spec.ts",
    "api/managed-volume-sizing.spec.ts",
    "api/management-image-backup-domain.spec.ts",
    "api/management-worker-domain.spec.ts",
    "api/provider-http.spec.ts",
    "api/resource-monitor-lifecycle.spec.ts",
    "api/worker-self-access-policy.spec.ts",
    "api/ws-relay-origin.spec.ts",
    "api/worker-runtime-kind.spec.ts",
    "api/worker-incus-migration-fencing.spec.ts",
    "api/worker-incus-migration-store.spec.ts",
    "api/worker-backup-runtime.spec.ts",
    "api/worker-import-runtime-policy.spec.ts",
    "api/worker-import-runtime-routing.spec.ts",
    "api/worker-import-image-resolution.spec.ts",
    "api/management-import-domain.spec.ts",
    "api/worker-export-format.spec.ts",
    "api/worker-reconstruction.spec.ts",
    "api/worker-lifecycle-coordinator.spec.ts",
    "api/incus-client.spec.ts",
    "api/incus-image-import.spec.ts",
    "api/incus-image-import-live.spec.ts",
    "api/incus-image-converter.spec.ts",
    "api/incus-image-converter-live.spec.ts",
    "api/incus-converted-image-boot-live.spec.ts",
    "api/incus-image-artifact.spec.ts",
    "api/incus-worker-image-manager.spec.ts",
    "api/catalog-native-binding.spec.ts",
    "api/image-catalog-hierarchy.spec.ts",
    "api/incus-exec-transport.spec.ts",
    "api/incus-worker-commands.spec.ts",
    "api/incus-worker-experience.spec.ts",
    "api/incus-derived-image.spec.ts",
    "api/incus-worker-runtime.spec.ts",
    "api/incus-canonical-archive.spec.ts",
    "api/incus-offline-archive-helper.spec.ts",
    "api/incus-original-workspace-live.spec.ts",
    "api/incus-original-workspace-runtime.spec.ts",
    "api/incus-workspace-replace-script.spec.ts",
    "api/incus-offline-canonical.spec.ts",
    "api/incus-worker-backup-live.spec.ts",
    "api/incus-worker-backup-fence.spec.ts",
    "api/incus-worker-lifecycle.spec.ts",
    "api/incus-applied-bootstrap.spec.ts",
    "api/incus-worker-observability.spec.ts",
    "api/incus-worker-network.spec.ts",
    "api/incus-traefik-routing.spec.ts",
    "api/incus-deployment-config.spec.ts",
    "api/incus-host-setup-live.spec.ts",
    "api/incus-guest-network.spec.ts",
    "api/incus-full-stack.spec.ts",
    "api/incus-worker-storage.spec.ts",
    "api/incus-managed-volume.spec.ts",
    "api/incus-managed-volume-runtime.spec.ts",
    "api/incus-volume-inventory.spec.ts",
    "api/incus-volume-size-helper.spec.ts",
    "api/incus-managed-network-capability.spec.ts",
    "api/incus-managed-network-host.spec.ts",
    "api/incus-managed-network-runtime.spec.ts",
    "api/incus-live-volume-helper.spec.ts",
    "api/incus-account-sharing.spec.ts",
    "api/incus-private-storage.spec.ts",
    "api/workspace-download-cancellation.spec.ts",
  ],
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: [["list"]],
  timeout: 30_000,
});
