<script setup lang="ts">
import type { HardwareDeviceGrantTarget } from '../../shared/types';
const open = defineModel<boolean>('open', { default: false });
const { client, user, isAdmin } = useAuth(); const hardware = useHardwareDevices();
interface UserRow { id: string; name: string; email: string }
const users = ref<UserRow[]>([]); const selectedOwnerId = ref(''); const actionError = ref(''); const saving = ref(false);
const approval = reactive({ selector: '', name: '' });
const assignment = reactive({ deviceId: '', targetType: 'all' as Exclude<HardwareDeviceGrantTarget, 'entitlement'>, targetId: '' });
const entitled = computed(() => hardware.view.value?.catalog.filter((item) => item.entitled) ?? []);
const deviceById = computed(() => new Map((hardware.view.value?.catalog ?? []).map((item) => [item.id, item])));
const groupById = computed(() => new Map((hardware.view.value?.groups ?? []).map((item) => [item.id, item])));
const workerById = computed(() => new Map((hardware.view.value?.workers ?? []).map((item) => [item.id, item])));
const targets = computed(() => assignment.targetType === 'group' ? (hardware.view.value?.groups ?? []).map((item) => ({ label: item.name, value: item.id })) : (hardware.view.value?.workers ?? []).map((item) => ({ label: `${item.displayName} (${item.status})`, value: item.id })));
function message(cause: any) { return cause?.data?.statusMessage || cause?.data?.message || cause?.message || 'Hardware device operation failed.'; }
async function loadUsers() { if (!isAdmin.value) { selectedOwnerId.value = (user.value as any)?.id || ''; return; } const result = await client.admin.listUsers({ query: { limit: 500, sortBy: 'email', sortDirection: 'asc' } }); if ((result as any)?.error) throw new Error((result as any).error.message); users.value = ((result as any)?.data?.users ?? (result as any)?.data ?? []) as UserRow[]; if (!selectedOwnerId.value) selectedOwnerId.value = (user.value as any)?.id || users.value[0]?.id || ''; }
async function reload() { if (!selectedOwnerId.value) return; await hardware.refresh({ ownerId: selectedOwnerId.value }); if (!assignment.deviceId || !entitled.value.some((item) => item.id === assignment.deviceId)) assignment.deviceId = entitled.value[0]?.id || ''; if (!approval.selector || !hardware.view.value?.discovered.some((item) => item.selector === approval.selector)) approval.selector = hardware.view.value?.discovered[0]?.selector || ''; }
watch(open, async (shown) => { if (!shown) return; actionError.value = ''; try { await loadUsers(); await reload(); } catch (cause) { actionError.value = message(cause); } });
watch(selectedOwnerId, () => { if (open.value) void reload(); }); watch(() => assignment.targetType, () => { assignment.targetId = ''; });
async function run(operation: () => Promise<unknown>) { saving.value = true; actionError.value = ''; try { await operation(); await reload(); } catch (cause) { actionError.value = message(cause); } finally { saving.value = false; } }
async function approve() { await run(() => $fetch('/api/hardware-devices', { method: 'POST', body: { selector: approval.selector, name: approval.name.trim() || undefined } })); approval.name = ''; }
function renameDevice(id: string) { const current = deviceById.value.get(id); const name = prompt('Device display name', current?.name || ''); if (!name?.trim()) return; return run(() => $fetch(`/api/hardware-devices/${id}`, { method: 'PATCH', body: { name } })); }
function deleteDevice(id: string) { if (!confirm('Delete this approved device? Dependent assignments will be revoked and affected workers stopped.')) return; return run(() => $fetch(`/api/hardware-devices/${id}`, { method: 'DELETE' })); }
function setEntitlement(deviceId: string, enabled: boolean) { return run(() => $fetch('/api/hardware-devices/entitlements', { method: 'PUT', body: { ownerId: selectedOwnerId.value, deviceId, enabled } })); }
function createGrant() { if (!assignment.deviceId || (assignment.targetType !== 'all' && !assignment.targetId)) return; return run(() => $fetch('/api/hardware-devices/grants', { method: 'POST', body: { ownerId: selectedOwnerId.value, deviceId: assignment.deviceId, targetType: assignment.targetType, ...(assignment.targetType === 'all' ? {} : { targetId: assignment.targetId }) } })); }
function deleteGrant(id: string) { if (!confirm('Revoke this device assignment and derived delegations? Affected workers will stop until rebuilt.')) return; return run(() => $fetch(`/api/hardware-devices/grants/${id}`, { method: 'DELETE', query: { ownerId: selectedOwnerId.value } })); }
function targetLabel(grant: any) { if (grant.targetType === 'all') return 'All workers'; if (grant.targetType === 'group') return `Group: ${groupById.value.get(grant.targetId)?.name || grant.targetId}`; return `Worker: ${workerById.value.get(grant.targetId)?.displayName || grant.targetId}`; }
</script>
<template>
  <UModal v-model:open="open" :ui="{ content: 'sm:max-w-5xl' }"><template #content>
    <div class="max-h-[90vh] space-y-5 overflow-y-auto p-6" data-testid="hardware-device-management">
      <div class="flex items-center justify-between"><div><h2 class="text-lg font-semibold">Hardware device permissions</h2><p class="text-sm text-gray-500">Discover, approve, entitle, and assign GPUs or USB devices without exposing raw host paths.</p></div><UButton color="neutral" variant="ghost" @click="() => { open = false; }">Close</UButton></div>
      <UAlert color="warning" variant="soft" icon="i-lucide-cpu" title="Hardware access is security-sensitive" description="A worker with a device can communicate with that host hardware. Grant only devices the worker needs." />
      <p v-if="actionError || hardware.error.value" class="text-sm text-red-600">{{ actionError || hardware.error.value }}</p>
      <section v-if="isAdmin" class="space-y-3 rounded-lg border border-red-300 p-4 dark:border-red-900">
        <div><h3 class="font-medium text-red-800 dark:text-red-200">Platform device catalog</h3><p class="text-xs text-gray-500">The dropdown contains live host devices. Approval stores a stable identity; node paths are resolved again at rebuild.</p></div>
        <div v-if="hardware.view.value?.discovered.length" class="grid gap-2 md:grid-cols-[2fr_2fr_auto]"><USelect v-model="approval.selector" :items="hardware.view.value.discovered.map((item) => ({ label: `${item.name} · ${item.deviceNodes.join(', ')}`, value: item.selector }))" placeholder="Discovered device" /><UInput v-model="approval.name" placeholder="Optional display name" /><UButton :disabled="!approval.selector" :loading="saving" @click="approve">Approve device</UButton></div>
        <p v-else class="text-sm text-gray-500">No unapproved GPU or USB devices are currently available.</p>
        <div v-if="hardware.view.value?.catalog.length" class="divide-y rounded border"><div v-for="device in hardware.view.value.catalog" :key="device.id" class="flex items-center gap-3 p-3 text-sm"><UIcon :name="device.kind === 'gpu' ? 'i-lucide-monitor-up' : 'i-lucide-usb'" /><div class="min-w-0 flex-1"><div class="font-medium">{{ device.name }} <UBadge size="xs" :color="device.available ? 'success' : 'warning'">{{ device.available ? 'available' : 'unavailable' }}</UBadge></div><code class="text-xs text-gray-500">{{ device.selector }}</code></div><UButton size="xs" color="neutral" variant="ghost" @click="renameDevice(device.id)">Rename</UButton><UButton size="xs" color="error" variant="ghost" @click="deleteDevice(device.id)">Delete</UButton></div></div>
      </section>
      <section class="space-y-3 rounded-lg border p-4"><div class="flex items-end gap-3"><div class="flex-1"><h3 class="font-medium">Account entitlements</h3><p class="text-xs text-gray-500">Platform administrators choose which devices this account may assign.</p></div><UFormField v-if="isAdmin" label="Account"><USelect v-model="selectedOwnerId" :items="users.map((item) => ({ label: `${item.name} (${item.email})`, value: item.id }))" class="min-w-72" /></UFormField></div>
        <div class="grid gap-2 md:grid-cols-2"><label v-for="device in hardware.view.value?.catalog" :key="device.id" class="flex items-center gap-2 rounded border p-2 text-sm"><UCheckbox :model-value="device.entitled" :disabled="!isAdmin || saving" @update:model-value="setEntitlement(device.id, $event === true)" /><span>{{ device.name }} <span class="text-xs text-gray-500">({{ device.kind }})</span></span></label></div>
      </section>
      <section class="space-y-3 rounded-lg border p-4"><div><h3 class="font-medium">Assignments</h3><p class="text-xs text-gray-500">A group assignment covers its direct workers and lets that group's administrator delegate only within its subtree.</p></div>
        <div v-if="entitled.length" class="grid gap-2 md:grid-cols-[2fr_1fr_2fr_auto]"><USelect v-model="assignment.deviceId" :items="entitled.map((item) => ({ label: item.name, value: item.id }))" /><USelect v-model="assignment.targetType" :items="[{label:'All workers',value:'all'},{label:'Group',value:'group'},{label:'Worker',value:'worker'}]" /><USelect v-if="assignment.targetType !== 'all'" v-model="assignment.targetId" :items="targets" placeholder="Select target" /><div v-else/><UButton :loading="saving" @click="createGrant">Assign</UButton></div>
        <UAlert v-else color="neutral" variant="soft" title="No entitled devices" description="A platform administrator must entitle a device before it can be assigned." />
        <div v-if="hardware.view.value?.grants.length" class="divide-y rounded border"><div v-for="grant in hardware.view.value.grants" :key="grant.id" class="flex items-center gap-3 p-3 text-sm"><div class="flex-1"><span class="font-medium">{{ deviceById.get(grant.deviceId)?.name || grant.deviceId }}</span><span class="text-gray-500"> · {{ targetLabel(grant) }}</span><UBadge v-if="grant.grantorType === 'group'" size="xs" color="info" class="ml-2">delegated</UBadge></div><UButton v-if="grant.grantorType !== 'group'" size="xs" color="error" variant="ghost" @click="deleteGrant(grant.id)">Revoke</UButton></div></div>
      </section>
      <UAlert color="info" variant="soft" title="Group administrative workspaces" description="Their management MCP can inspect devices granted to the group and delegate them only to descendant groups or workers in that subtree." />
    </div>
  </template></UModal>
</template>
