<script setup lang="ts">
import type { ContainerInfo } from '~/types';
const open = defineModel<boolean>('open', { default: false });
const props = defineProps<{ containers: ContainerInfo[] }>();
const { networks, create, update, remove, validate } = useManagedNetworks();
const groups = ref<any[]>([]); const name = ref(''); const scope = ref<'all'|'selected'|'group'>('selected'); const groupId = ref(''); const error = ref(''); const feedback = ref<Record<string, string>>({});
watch(open, async shown => { if (!shown) return; groups.value = await $fetch<any[]>('/api/worker-groups').catch(() => []); });
async function add() { try { error.value=''; if (!name.value.trim()) return; await create({ name:name.value, scope:scope.value, ...(scope.value==='group'?{groupId:groupId.value}:{}) }); name.value=''; } catch(e:any) { error.value=e?.data?.statusMessage||'Could not create network.'; } }
async function save(network:any, body:any) { try { const result=await update(network.id,body); const failures=result?.reconciliation?.partialFailures||[]; feedback.value[network.id]=failures.length?failures.join('; '):'Membership applied.'; } catch(e:any) { feedback.value[network.id]=e?.data?.statusMessage||'Update failed.'; } }
async function toggle(network:any,id:string){await save(network,{workerIds:network.workerIds.includes(id)?network.workerIds.filter((x:string)=>x!==id):[...network.workerIds,id]})}
async function inspect(network:any){try{const result=await validate(network.id);feedback.value[network.id]=result.ok?'Connectivity membership verified.':`Missing: ${(result.missingWorkerIds||[]).join(', ')||'none'}; unexpected: ${(result.unexpected||[]).map((x:any)=>x.name).join(', ')||'none'}`;}catch(e:any){feedback.value[network.id]=e?.data?.statusMessage||'Validation failed.'}}
async function rename(network:any){const value=prompt('Network name',network.name);if(value?.trim())await save(network,{name:value});}
const groupName=(id?:string)=>groups.value.find(group=>group.id===id)?.name||'deleted group';
</script>
<template><UModal v-model:open="open" title="Managed networks" data-testid="managed-networks"><template #body><form class="grid gap-2 md:grid-cols-4" @submit.prevent="add"><UInput v-model="name" aria-label="Network name" placeholder="Network name"/><select v-model="scope" aria-label="Network scope" class="rounded border p-2"><option value="selected">Selected workers</option><option value="all">All my workers</option><option value="group">Worker group</option></select><select v-if="scope==='group'" v-model="groupId" aria-label="Worker group" class="rounded border p-2"><option value="">Choose group</option><option v-for="group in groups" :key="group.id" :value="group.id">{{group.name}}</option></select><UButton type="submit">Create network</UButton></form><p v-if="error" role="alert" class="text-red-600 text-sm">{{error}}</p><p class="mt-2 text-xs text-gray-500">Management networks are never attachable here. Network membership is applied by the orchestrator.</p><section v-for="network in networks" :key="network.id" class="mt-4 rounded border p-3"><div class="flex justify-between"><div><strong>{{network.name}}</strong><span class="ml-2 text-xs text-gray-500">{{network.scope==='all'?'all workers':network.scope==='group'?`group: ${groupName(network.groupId)}`:'selected workers'}}</span></div><span><UButton size="xs" variant="ghost" @click="rename(network)">Rename</UButton><UButton size="xs" variant="ghost" @click="inspect(network)">Validate</UButton><UButton size="xs" color="error" variant="ghost" @click="remove(network.id)">Delete</UButton></span></div><p v-if="feedback[network.id]" class="mt-2 text-xs" :class="feedback[network.id].includes('applied')||feedback[network.id].includes('verified')?'text-green-700':'text-amber-700'">{{feedback[network.id]}}</p><template v-if="network.scope==='selected'"><label v-for="worker in props.containers.filter(x=>x.userId===network.userId)" :key="worker.id" class="block mt-2"><input type="checkbox" :checked="network.workerIds.includes(worker.id)" @change="toggle(network,worker.id)"> {{worker.displayName}}</label></template></section></template></UModal></template>
