import { createHash } from 'node:crypto';
import type { Config } from './config';
import { IncusClient, type IncusCustomVolume } from './incus-client';
import { IncusWorkerStorage } from './incus-worker-storage';
import type { IncusManagedVolumeRuntime } from './incus-managed-volume-runtime';
import { managedVolumeRuntimeKind, type StoredManagedVolume } from './managed-volume-store';
import type { WorkerRecord } from './worker-store';

export interface IncusVolumeInventoryResource {
  id: string;
  name: string;
  userId: string;
  workerId: string;
  ownerKey: string;
  purpose: string;
  classification: 'managed' | 'builtin';
  target: string;
  status: 'present' | 'missing' | 'unavailable' | 'foreign' | 'quarantined';
  volume?: IncusCustomVolume;
  incarnation?: string;
  attached?: boolean;
  live?: boolean;
  instanceIncarnation?: string;
  deviceKey?: string;
}

export interface IncusVolumeInventoryDependencies {
  /** Existing adapter; discovery never calls ensureVolume or exec. */
  managed: Pick<IncusManagedVolumeRuntime, 'inspectVolume'>;
  client?: IncusClient;
  isRecoveryBlocked?: (workerId: string) => boolean;
}

const uuid = /^[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}$/i;
const builtinId = (name: string) => `builtin-${createHash('sha256').update(name).digest('hex').slice(0, 24)}`;

/** Only durable Incus resources, never daemon-wide discovery or adoption.
 * installationId is established by platform initialization, not generated by
 * this read-only operation. Each failed resource leaves unrelated ones usable. */
export async function discoverIncusVolumes(config: Config, installationId: string,
  workers: WorkerRecord[], records: StoredManagedVolume[], deps: IncusVolumeInventoryDependencies,
): Promise<Map<string, IncusVolumeInventoryResource>> {
  const client = deps.client ?? IncusClient.fromConfig(config);
  const storage = new IncusWorkerStorage(client, config, installationId);
  const result = new Map<string, IncusVolumeInventoryResource>();
  const owners = new Map(workers.map(worker => [worker.id, worker]));
  const instances = new Map<string, ReturnType<IncusClient['getInstance']>>();
  const inspect = async (resource: IncusVolumeInventoryResource, read: () => Promise<IncusCustomVolume | undefined>,
    identity: Record<string, string>, quarantined: boolean) => {
    result.set(resource.id, resource);
    if (!uuid.test(installationId) || quarantined || deps.isRecoveryBlocked?.(resource.workerId)) {
      resource.status = 'quarantined'; return;
    }
    try {
      const volume = await read();
      if (!volume) { resource.status = 'missing'; return; }
      resource.volume = volume;
      const expectedType = resource.purpose === 'docker-in-docker' ? 'block' : 'filesystem';
      if (volume.project !== config.incusProject || volume.name !== resource.name || volume.type !== 'custom' ||
          volume.content_type !== expectedType || !Array.isArray(volume.used_by) ||
          Object.entries(identity).some(([key, value]) => volume.config[key] !== value)) {
        resource.status = 'foreign'; return;
      }
      if (typeof volume.created_at !== 'string' ||
          !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(volume.created_at) ||
          !Number.isFinite(Date.parse(volume.created_at)) || Date.parse(volume.created_at) <= 0) {
        resource.status = 'quarantined'; return;
      }
      if (volume.used_by.length > 1) { resource.status = 'foreign'; return; }
      resource.attached = volume.used_by.length === 1;
      resource.live = false;
      if (resource.attached) {
        const name = `${config.containerPrefix}-${resource.workerId}`;
        const ref = new URL(volume.used_by[0]!, client.endpoint);
        if (ref.origin !== new URL(client.endpoint).origin || ref.username || ref.password || ref.hash ||
            ref.pathname !== `/1.0/instances/${name}` || ref.searchParams.getAll('project').length !== 1 ||
            ref.searchParams.get('project') !== config.incusProject || [...ref.searchParams.keys()].some(key => key !== 'project')) {
          resource.status = 'foreign'; return;
        }
        const worker = owners.get(resource.workerId);
        if (!worker || worker.userId !== resource.userId || worker.runtimeKind !== 'incus-vm' ||
            worker.status !== 'active' || worker.deletionPending || worker.incusRecreation) {
          resource.status = 'quarantined'; return;
        }
        if (!instances.has(name)) instances.set(name, client.getInstance(name));
        const instance = await instances.get(name)!;
        const c = instance.config;
        if (instance.name !== name || instance.type !== 'virtual-machine' ||
            c['user.agentor.installation'] !== installationId || c['user.agentor.owner'] !== resource.userId ||
            c['user.agentor.id'] !== resource.workerId || !uuid.test(c['volatile.uuid'] ?? '')) {
          resource.status = 'foreign'; return;
        }
        const disks = Object.entries(instance.expanded_devices ?? instance.devices).filter(([, d]) =>
          d.type === 'disk' && d.source === resource.name && d.pool === config.incusStoragePool);
        if (disks.length !== 1 || !/^[a-zA-Z0-9_-]+$/.test(disks[0]![0]) ||
            (expectedType === 'filesystem' ? disks[0]![1].path !== resource.target : !!disks[0]![1].path)) {
          resource.status = 'foreign'; return;
        }
        if (!['Running', 'Stopped'].includes(instance.status)) { resource.status = 'unavailable'; return; }
        resource.live = instance.status === 'Running';
        resource.instanceIncarnation = c['volatile.uuid'];
        resource.deviceKey = disks[0]![0];
      }
      resource.incarnation = createHash('sha256').update(JSON.stringify({
        project: config.incusProject, pool: config.incusStoragePool, name: volume.name,
        content: volume.content_type, created: volume.created_at, identity,
      })).digest('hex');
      resource.status = 'present';
    } catch (error) {
      const status = (error as { statusCode?: number }).statusCode;
      resource.status = status === 409 || status === 400 || (error as Error).message?.includes('ownership/type') ||
        (error as Error).message?.includes('another runtime') ? 'foreign' : 'unavailable';
    } finally {
      // Unknown observations must not accidentally become offline scan authority.
      if (resource.status !== 'present') {
        resource.live = undefined; resource.attached = undefined;
        resource.incarnation = undefined; resource.instanceIncarnation = undefined;
        resource.deviceKey = undefined;
      }
    }
  };
  for (const v of records) {
    if (managedVolumeRuntimeKind(v) !== 'incus-vm') continue;
    const worker = owners.get(v.workerId);
    await inspect({ id: v.id, name: v.dockerName, userId: v.userId, workerId: v.workerId,
      ownerKey: v.retainedAfterAccountDeletion ? 'platform' : v.userId, purpose: v.purpose,
      classification: 'managed', target: v.target, status: 'unavailable' }, () => deps.managed.inspectVolume(v), {
      'user.agentor.installation': installationId, 'user.agentor.owner': v.userId, 'user.agentor.id': v.workerId,
      'user.agentor.volume-id': v.id, 'user.agentor.target': v.target,
    }, !!v.incusLive || !!v.liveContainerId || !!v.previousRestartPolicy || v.state === 'preparing' || v.state === 'failed' ||
      !!worker && (worker.runtimeKind !== 'incus-vm' || worker.userId !== v.userId || !!worker.incusRecreation || !!worker.deletionPending));
  }
  for (const worker of workers) {
    if (worker.runtimeKind !== 'incus-vm') continue;
    const owner = { id: worker.id, userId: worker.userId, containerName: `${config.containerPrefix}-${worker.id}` };
    for (const role of ['workspace', 'agents', 'docker'] as const) {
      const name = `${owner.containerName}-${role}`;
      await inspect({ id: builtinId(name), name, userId: worker.userId, workerId: worker.id, ownerKey: worker.userId,
        purpose: role === 'agents' ? 'agent-data' : role === 'docker' ? 'docker-in-docker' : role,
        classification: 'builtin', target: role === 'workspace' ? '/workspace' : role === 'agents' ? '/home/agent/.agent-data' : '/var/lib/docker',
        status: 'unavailable' }, () => storage.inspectVolume(owner, role), {
        'user.agentor.installation': installationId, 'user.agentor.owner': worker.userId,
        'user.agentor.id': worker.id, 'user.agentor.storage-role': role,
      }, !!worker.incusRecreation || !!worker.deletionPending);
    }
  }
  return result;
}
