import { useContainerManager } from './services';
import { useWorkerProtectionLockStore } from './worker-protection-lock';
const read={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false},mut={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false};
type Tool={name:string;group:'running-files';description:string;inputSchema:Record<string,unknown>;annotations:Record<string,boolean>};
/** Bounded JSON-RPC adapter over ContainerManager's already hardened running
 * workspace file manager. It never receives a host path or Docker handle. */
export class ManagementRunningFilesDomain { tools():Tool[]{const worker={workerId:{type:'string'},lockPassword:{type:'string',writeOnly:true}};return[
  tool('files.list','List a running worker workspace directory.',{type:'object',required:['workerId'],properties:{...worker,path:{type:'string'}}},read),
  tool('files.upload','Upload one base64 file (maximum 1 MiB) to a running workspace.',{type:'object',required:['workerId','path','base64'],properties:{...worker,path:{type:'string'},base64:{type:'string'},overwrite:{type:'boolean'}}},mut),
  tool('files.mkdir','Create a workspace directory.',{type:'object',required:['workerId','path'],properties:{...worker,path:{type:'string'}}},mut),
  tool('files.rename','Rename one workspace entry.',{type:'object',required:['workerId','path','newName'],properties:{...worker,path:{type:'string'},newName:{type:'string'}}},mut),
  tool('files.move','Move entries to a workspace directory.',{type:'object',required:['workerId','paths','destination'],properties:{...worker,paths:{type:'array',items:{type:'string'}},destination:{type:'string'},overwrite:{type:'boolean'}}},mut),
  tool('files.delete','Delete workspace entries.',{type:'object',required:['workerId','paths'],properties:{...worker,paths:{type:'array',items:{type:'string'}}}}, {...mut,destructiveHint:true})];}
  async execute(name:string,args:Record<string,unknown>){if(!this.tools().some(x=>x.name===name))return{handled:false};const cm=useContainerManager(),id=req(args.workerId,'workerId');if(name==='files.list')return{handled:true,result:await cm.listFiles(id,str(args.path))};await useWorkerProtectionLockStore().verify(id,args.lockPassword);if(name==='files.mkdir')return{handled:true,result:await cm.mkdirFiles(id,str(args.path))};if(name==='files.rename')return{handled:true,result:await cm.renameFile(id,str(args.path),req(args.newName,'newName'))};if(name==='files.move')return{handled:true,result:await cm.moveFiles(id,strings(args.paths),str(args.destination),args.overwrite===true)};if(name==='files.delete')return{handled:true,result:await cm.deleteFiles(id,strings(args.paths))};const encoded=req(args.base64,'base64');if(encoded.length>1398104||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(encoded))throw fail(400,'base64 must be valid and encode at most 1 MiB');const data=Buffer.from(encoded,'base64');if(data.length>1024*1024)throw fail(413,'MCP file upload is limited to 1 MiB');return{handled:true,result:await cm.uploadFiles(id,'',[{rel:str(args.path),data}],args.overwrite===true)};}}
function tool(name:string,description:string,inputSchema:Record<string,unknown>,annotations:Record<string,boolean>):Tool{return{name,group:'running-files',description,inputSchema,annotations}}function req(v:unknown,n:string){if(typeof v!=='string'||!v)throw fail(400,`${n} is required`);return v}function str(v:unknown){return typeof v==='string'?v:''}function strings(v:unknown){if(!Array.isArray(v)||!v.length||v.some(x=>typeof x!=='string'))throw fail(400,'paths must be non-empty strings');return v as string[]}function fail(statusCode:number,message:string){return Object.assign(new Error(message),{statusCode})}
