import { useImageCatalogManager } from "./image-catalog";
import { useBackupManager } from "./backup-manager";
import { useGitImageCatalogManager } from "./git-image-manager";

export interface ImageBackupTool { name:string; group:"images"|"backups"; description:string; inputSchema:Record<string,unknown>; annotations:Record<string,boolean>; }
const ro={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}; const mut={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false};
/** Transport-free MCP adapter for image catalog and backup services. All calls
 * go through existing managers; secrets/tokens are never returned. */
export class ManagementImageBackupDomain {
  tools():ImageBackupTool[]{return [
    ["images.list","images","List an owner's definitions",ro],["images.get","images","Get a definition",ro],["images.create","images","Create validated definition",mut],["images.validate","images","Validate definition",ro],["images.delete","images","Delete an unused definition",{...mut,destructiveHint:true}],["images.build","images","Start controlled build",mut],["images.build-status","images","Read build state",ro],["images.build-logs","images","Read sanitized build logs",ro],["images.build-cancel","images","Cancel build",{...mut,destructiveHint:true}],["images.promote","images","Promote version",mut],["images.rollback","images","Roll back promoted version",mut],["images.default","images","Set owner/system default",mut],["images.cleanup","images","Remove unused artifacts",{...mut,destructiveHint:true}],["images.git-status","images","Read safe Git catalog status",ro],["images.git-sync","images","Synchronize configured Git catalog",mut],
    ["backups.list","backups","List sanitized backups/jobs/settings",ro],["backups.providers","backups","List provider status without tokens",ro],["backups.settings","backups","Read or set safe backup settings",mut],["backups.create","backups","Start backup for owner's workspaces",mut],["backups.status","backups","Read job status",ro],["backups.cancel","backups","Cancel job",{...mut,destructiveHint:true}],["backups.retry","backups","Retry failed job",mut],["backups.delete","backups","Delete backup artifact",{...mut,destructiveHint:true}],["backups.restore","backups","Start safe restore job",mut]
  ].map(([name,group,description,annotations])=>({name:name as string,group:group as "images"|"backups",description:description as string,inputSchema:{type:"object",additionalProperties:true},annotations:annotations as any}));}
  async execute(name:string,args:Record<string,unknown>){if(!this.tools().some(t=>t.name===name))return{handled:false}; if(name.startsWith("images."))return{handled:true,result:await this.images(name,args)};return{handled:true,result:await this.backups(name,args)};}
  private async images(name:string,a:Record<string,unknown>):Promise<any>{const catalog=useImageCatalogManager();await catalog.init();const owner=required(a.ownerId,"ownerId");const id=string(a.definitionId);if(name==="images.list")return catalog.list(owner,true);if(name==="images.create")return catalog.create(owner,a.definition);if(name==="images.validate")return catalog.validate(a.definition);if(name==="images.get")return catalog.definition(required(id,"definitionId"),owner,true);if(name==="images.delete"){await catalog.removeDefinition(required(id,"definitionId"),owner,true);return{deleted:true};}if(name==="images.build")return catalog.startBuild(required(id,"definitionId"),owner,true,{builder:a.builder==="fake"?"fake":"controlled",baseImage:a.baseImage});if(name==="images.build-status")return catalog.publicBuild(required(string(a.buildId),"buildId"),owner,true);if(name==="images.build-logs")return{logs:catalog.logs(required(string(a.buildId),"buildId"),owner,true,number(a.after,0))};if(name==="images.build-cancel")return catalog.cancelBuild(required(string(a.buildId),"buildId"),owner,true);if(name==="images.promote")return catalog.promote(required(id,"definitionId"),required(a.version,"version"),owner,true);if(name==="images.rollback")return catalog.rollback(required(id,"definitionId"),required(a.version,"version"),owner,true);if(name==="images.default")return a.system===true?catalog.setSystemDefault(required(id,"definitionId"),required(a.version,"version"),owner):catalog.setUserDefault(owner,required(id,"definitionId"),required(a.version,"version"));if(name==="images.cleanup")return catalog.cleanup(owner,true,a);const git=useGitImageCatalogManager();if(name==="images.git-status")return sanitize({connection:git.connection(owner),recovery:git.recovery(owner)});if(name==="images.git-sync")return git.sync(owner,catalog,a);throw fail(400,"Unknown image tool");}
  private async backups(name:string,a:Record<string,unknown>):Promise<any>{const manager=useBackupManager();await manager.init();const owner=required(a.ownerId,"ownerId");if(name==="backups.list")return sanitize(await manager.list(owner));if(name==="backups.providers")return sanitize(manager.providersStatus(owner));if(name==="backups.settings"){if(a.settings!==undefined)return sanitize(await manager.setConfig(owner,a.settings as any));return sanitize(await manager.getConfig(owner));}if(name==="backups.create")return manager.createMany(owner,strings(a.workspaceIds,"workspaceIds"));if(name==="backups.restore"||name==="backups.delete"){const artifact=await manager.getArtifact(required(a.artifactId,"artifactId"));if(!artifact||artifact.userId!==owner)throw fail(404,"Backup artifact not found");if(name==="backups.restore")return sanitize(await manager.createRestore(owner,artifact,"new",string(a.displayName)));await manager.deleteArtifact(artifact);return{deleted:true};}const job=await manager.getJob(required(a.jobId,"jobId"));if(!job||job.userId!==owner)throw fail(404,"Backup job not found");if(name==="backups.status")return sanitize(job);if(name==="backups.cancel")return sanitize(await manager.cancel(job));if(name==="backups.retry")return sanitize(await manager.retry(job));throw fail(400,"Unknown backup tool");}
}
function required(v:unknown,n:string){if(typeof v!=="string"||!v)throw fail(400,`${n} is required`);return v;}function string(v:unknown){return typeof v==="string"?v:undefined;}function number(v:unknown,d:number){return typeof v==="number"&&Number.isSafeInteger(v)&&v>=0?v:d;}function strings(v:unknown,n:string){if(!Array.isArray(v)||!v.length||v.some(x=>typeof x!=="string"))throw fail(400,`${n} is required`);return [...new Set(v as string[])];}function fail(statusCode:number,message:string){return Object.assign(new Error(message),{statusCode});}
function sanitize(value:any):any {
  if (Array.isArray(value)) return value.map(sanitize);
  if (value && typeof value === "object") return Object.fromEntries(
    Object.entries(value).map(([key, item]) =>
      /token|secret|credential|password|authorization/i.test(key)
        ? [key, "[REDACTED]"]
        : [key, sanitize(item)],
    ),
  );
  return value;
}
